//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesoria_antropometria
    {
        public int Id { get; set; }
        public int Id_mensualidad { get; set; }
        public double Peso { get; set; }
        public int Altura { get; set; }
        public double IMC { get; set; }
        public double Brazo_derecho_relajado { get; set; }
        public double Brazo_derecho_fuerza { get; set; }
        public double Brazo_izquierdo_relajado { get; set; }
        public double Brazo_izquierdo_fuerza { get; set; }
        public double Cintura { get; set; }
        public double Cadera { get; set; }
        public double Pierna_izquierda { get; set; }
        public double Pierna_derecho { get; set; }
        public double Pantorrilla_derecha { get; set; }
        public double Pantorrilla_izquierda { get; set; }
        public string Foto_frontal { get; set; }
        public string Foto_perfil { get; set; }
        public string Foto_posterior { get; set; }
        public System.DateTime Fecha_registro { get; set; }
    }
}
