//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_rutina
    {
        public int Id_detalle_rutina { get; set; }
        public int Id_mensualidad { get; set; }
        public int Id_rutina { get; set; }
        public int Id_ejercicio { get; set; }
        public int Id_dia { get; set; }
        public int Repeticiones { get; set; }
        public int Series { get; set; }
        public int Tipo_set { get; set; }
    
        public virtual Dias Dias { get; set; }
        public virtual Ejercicios Ejercicios { get; set; }
        public virtual Mensualidad Mensualidad { get; set; }
        public virtual Rutina Rutinas { get; set; }
    }
}
