//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicios()
        {
            this.Detalle_rutinas = new HashSet<Detalle_rutinas>();
        }
    
        public int Id_ejercicio { get; set; }
        public string Clave_ejercicio { get; set; }
        public string Ejercicio { get; set; }
        public string Descripcion { get; set; }
        public string Ubicacion_imagen { get; set; }
        public string Posicion { get; set; }
        public int Id_rutina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_rutinas> Detalle_rutinas { get; set; }
        public virtual Rutinas Rutinas { get; set; }
    }
}
