//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensualidad()
        {
            this.Detalle_rutina = new HashSet<Detalle_rutina>();
        }
    
        public int Id_mensualidad { get; set; }
        public int Id_cliente { get; set; }
        public int Id_tipo_rutina { get; set; }
        public int Id_mes { get; set; }
        public int Id_estatus { get; set; }
        public int Id_tipo_entrenamiento { get; set; }
        public System.DateTime Fecha_inicio { get; set; }
        public System.DateTime Fecha_fin { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_rutina> Detalle_rutina { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Tipo_rutina Tipo_rutina { get; set; }
        public virtual Tipo_entrenamiento Tipo_entrenamiento { get; set; }
    }
}
