//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensualidades()
        {
            this.Asesoria_antropometria = new HashSet<Asesoria_antropometria>();
            this.Detalle_rutinas = new HashSet<Detalle_rutinas>();
            this.Pagos_mensualidades = new HashSet<Pagos_mensualidades>();
        }
    
        public int Id_mensualidad { get; set; }
        public int Id_cliente { get; set; }
        public int Id_tipo_rutina { get; set; }
        public int Id_mes { get; set; }
        public int Id_estatus { get; set; }
        public Nullable<int> Id_tipo_entrenamiento { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asesoria_antropometria> Asesoria_antropometria { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_rutinas> Detalle_rutinas { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Tipo_entrenamientos Tipo_entrenamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos_mensualidades> Pagos_mensualidades { get; set; }
        public virtual Meses Meses { get; set; }
        public virtual Tipo_rutinas Tipo_rutinas { get; set; }
    }
}
