//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id_usuario { get; set; }
        public string Clave_usuario { get; set; }
        public string Contraseña { get; set; }
        public string Nombres { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public bool Estado { get; set; }
    }
}
