//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesoria_Antropometria
    {
        public int Id { get; set; }
        public int Id_mensualidad { get; set; }
        public double Peso { get; set; }
        public int Altura { get; set; }
        public double IMC { get; set; }
        public double Brazoderechorelajado { get; set; }
        public double Brazoderechofuerza { get; set; }
        public double Brazoizquierdorelajado { get; set; }
        public double Brazoizquierdofuerza { get; set; }
        public double Cintura { get; set; }
        public double Cadera { get; set; }
        public double Piernaizquierda { get; set; }
        public double Piernaderecho { get; set; }
        public double Pantorrilladerecha { get; set; }
        public double Pantorrillaizquierda { get; set; }
        public System.DateTime Fecha_registro { get; set; }
    
        public virtual Mensualidad Mensualidad { get; set; }
    }
}
