//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperfitApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensualidad()
        {
            this.Asesoria_Antropometria = new HashSet<Asesoria_Antropometria>();
            this.Detalle_rutina = new HashSet<Detalle_rutina>();
        }
    
        public int Id_mensualidad { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_tiporutina { get; set; }
        public int Id_mes { get; set; }
        public int Id_estatus { get; set; }
        public Nullable<int> Id_TipoEntrenamiento { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asesoria_Antropometria> Asesoria_Antropometria { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_rutina> Detalle_rutina { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual TipoEntrenamiento TipoEntrenamiento { get; set; }
        public virtual Mensualidad Mensualidad1 { get; set; }
        public virtual Mensualidad Mensualidad2 { get; set; }
        public virtual Meses Meses { get; set; }
        public virtual Tiporutina Tiporutina { get; set; }
    }
}
